# Generated by Django 2.2.4 on 2021-10-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=30, unique=True, verbose_name='Nombre de Usuario')),
                ('correo', models.EmailField(max_length=30, unique=True, verbose_name='Correo electronico ')),
                ('nombres', models.CharField(max_length=30, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=30, null=True, verbose_name='Apellidos')),
                ('usuario_avtivo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
