# Generated by Django 2.2.4 on 2021-10-29 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creartarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tarea', models.CharField(max_length=30)),
                ('creacion_tarea', models.DateField(auto_now=True)),
                ('fecha_entrega', models.DateField()),
                ('descripcion', models.CharField(max_length=50, null=True)),
                ('referencia', models.CharField(max_length=30, null=True)),
                ('pendiente', models.BooleanField(null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crear tarea',
                'verbose_name_plural': 'Crear tareas',
            },
        ),
    ]
